service: cognito-node
app: cognito-node
frameworkVersion: "3"
custom:
  environment: ${env:NODE_ENV, 'dev'}
  application: CognitoNode
  stage: ${self:provider.stage}
  description: Cognito PoC

provider:
  name: aws
  runtime: nodejs14.x

  stage:  ${env:NODE_ENV, 'dev'}
  region: ${env:REGION, 'eu-central-1'}

  lambdaHashingVersion: 20201221
  stackName: ${self:service}-${opt:stage, self:provider.stage}-stack 
  apiName: ${self:service}-${opt:stage, self:provider.stage}-api 

  environment:
    NODE_ENV: ${env:NODE_ENV, 'dev'}
    SYSTEM: ${self:service}-${self:custom.environment}
    USERS_TABLE: users-${self:custom.environment}
    API_GATEWAY: ${self:custom.application}-CognitoPoC
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

  stackTags:
    service: ${self:service}
    application: ${self:custom.application}
  tags:
    application: ${self:custom.application}
    service: ${self:service}
    
plugins:
  - serverless-plugin-typescript 
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  hello:
    handler: src/functions/hello/index.handler
